### ISSUE TITLE
Erreur d'installation 

### ISSUE THREAD

**Issue by Lumino-2-0** [GeekMan44/Termux-Proot-GUI#2]
Bonjour monsieur GeekMan. J'ai sélectionné Ubuntu puis Gnome puis.... Voir le screen. Sûrement oublié d'installer un packagé ou juste problème de syntaxe ? J'ai bien pris la version pre-release-v.0.1.1
![Screenshot_20241013_233940](https://github.com/user-attachments/assets/732bce78-15e5-4de0-be16-d24786188792)

**Comment by GeekMan44** [comment]
Merci d'avoir reporté cette erreur il est vrai que j'ai oublié de la corriger sur les os Ubuntu Debian et Alpine. Je publierai une version corrigée dans la journée

**Comment by Lumino-2-0** [comment]
Merci de votre intervention.

**Comment by Lumino-2-0** [comment]
Après avoir installé le package propt-distro, la distribution à commencée à I
S'installer mais sans succès après la création de l'utilisateur et le MDP. Voir PJ :

![Screenshot_20241014_104233](https://github.com/user-attachments/assets/8c2d028b-c5b7-40ee-b7c5-72ab5bd7e8f9)
